=== sovereign-nature/deep/apps/gateway/json-schemas/metadata.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/address.schema.json",
  "title": "Identifier Token Metadata",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Lion name."
    },
    "description": {
      "type": "string",
      "description": "Lion description."
    },
    "image": {
      "type": "string",
      "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
    },
    "properties": {
      "type": "object",
      "description": "Identifier properties",
      "properties": {
        "statusDescription": {
          "type": "string",
          "description": "status field states description"
        },
        "taxonId": {
          "type": "string"
        },
        "conservationStatus": {
          "type": "string"
        },
        "geometry": {
          "type": "string"
        }
      }
    },
    "attributes": {
      "type": "array",
      "description": "Identifier attributes",
      "items": {
        "type": "object",
        "required": ["trait_type", "value"],
        "properties": {
          "trait_type": {
            "type": "string",
            "description": "The name of the trait being displayed."
          },
          "value": {
            "type": ["string", "number"],
            "description": "The value of the trait being displayed."
          }
        }
      },
      "minItems": 1
    }
  }
}

=== sovereign-nature/deep/apps/indexer/tests/ipfs/updated.json
{
  "name": "Sovereign Nature Identifier #1",
  "description": "Test lion identifier updated",
  "properties": {
    "statusDescription": "{ '0': 'Normal', '1': 'Aggressive' }",
    "taxonId": "itis:183803",
    "conservationStatus": "VU",
    "geometry": "POINT(6.0000 48.0000)"
  },
  "image": "ipfs://bafybeihs6qouvmo4pnjozlrdmgic3b4nav6rrswc3tobgclrrvtwsa47oe/blob"
}

=== sovereign-nature/deep/apps/indexer/tests/ipfs/initial.json
{
  "name": "Scarface",
  "description": "Test lion identifier",
  "properties": {
    "statusDescription": "{ \"0\": \"Alive\", \"1\": \"Dead\" }",
    "taxonId": "itis:183803",
    "conservationStatus": "VU",
    "geometry": "POINT(5.9559 47.8084)"
  },
  "attributes": [
    { "trait_type": "id", "value": "musm1" },
    { "trait_type": "gender", "value": "male" },
    { "trait_type": "birthday", "value": "january 2007" },
    { "trait_type": "coalition", "value": "musketeers" },
    {
      "trait_type": "prides",
      "value": "marsh pride, marsh breakaways, serena north, paradise breakaways, triangle lions"
    },
    { "trait_type": "unique_features", "value": "scared face" },
    { "trait_type": "whiskers_right_image_0", "value": "images/1/Image5.jpg" },
    { "trait_type": "whiskers_right_image_1", "value": "images/1/Image15.jpg" },
    { "trait_type": "whiskers_right_image_2", "value": "images/1/Image27.jpg" },
    { "trait_type": "whiskers_left_image_0", "value": "images/1/Image16.jpg" },
    { "trait_type": "whiskers_left_image_1", "value": "images/1/Image17.jpg" },
    { "trait_type": "whiskers_left_image_2", "value": "images/1/Image29.jpg" },
    { "trait_type": "ear_right", "value": "images/1/Image24.jpg" },
    { "trait_type": "ear_left", "value": "images/1/Image26.jpg" },
    { "trait_type": "face", "value": "images/1/Image28.jpg" }
  ],
  "image": "ipfs://bafybeihs6qouvmo4pnjozlrdmgic3b4nav6rrswc3tobgclrrvtwsa47oe/blob"
}
